MarioProducts/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using MarioProducts.Models;

namespace MarioProducts.Models
{
    [Table("Products")]
    public class Product
    {
        public Product()
        {
            this.Reviews = new HashSet<Review>();
        }

        [Key]
        public int ProductId { get; set; }
        [Required(ErrorMessage = "Product name required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Product price required")]
        public int Cost { get; set; }
        [Required(ErrorMessage = "Country of Origin required")]
        public string CountryOfOrigin { get; set; }

        public DateTime CreateDate {get; set;}

        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ApplicationUser Admin { get; set; }

		public override bool Equals(System.Object otherProduct)
		{
			if (!(otherProduct is Product))
			{
				return false;
			}
			else
			{
				Product newProduct = (Product)otherProduct;
				return this.ProductId.Equals(newProduct.ProductId);
			}
		}

		public override int GetHashCode()
		{
			return this.ProductId.GetHashCode();
		}

        public Product(string name, int cost, string countryOfOrigin, int productId)
        {
            this.Name = name;
            this.Cost = cost;
            this.CountryOfOrigin = countryOfOrigin;
            this.CreateDate = DateTime.Now;
            this.ProductId = productId;
        }

        public double AverageRating()
        {
            int avgRating = 0;

            foreach (var review in this.Reviews)
            {
                avgRating += review.Rating;
            }

            double average = (double)avgRating / this.Reviews.Count;

            return (Math.Truncate(average * 100) / 100);
        }

    }
}

MarioProducts/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using MarioProducts.Models;
using System.Diagnostics.Contracts;
using System.Security.Claims;

namespace MarioProducts.Controllers
{
    public class ProductController : Controller
    {
		private readonly MarioProductsDbContext _db;
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;

		public ProductController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, MarioProductsDbContext db)
		{
			_userManager = userManager;
			_signInManager = signInManager;
			_db = db;
		}

        public ViewResult Index()
        {
            return View(_db.Products.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Product product)
        {
			var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
			var currentUser = await _userManager.FindByIdAsync(userId);
			product.Admin = currentUser;
            product.CreateDate = DateTime.Now;
            _db.Products.Add(product);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var thisProduct = _db.Products.Include(x => x.Reviews)
                                 .FirstOrDefault(x => x.ProductId == id);
            //ViewBag.reviews = new SelectList(productRepo.Reviews, "ReviewId", "Author", "ContentBody", "Rating", "ProductId");
            return View(thisProduct);
        }

        public IActionResult Edit(int id)
        {
            var thisProduct = _db.Products.FirstOrDefault(x => x.ProductId == id);
            return View(thisProduct); 
        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            _db.Entry(product).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Details", new {id = product.ProductId});
        }

        public IActionResult Delete(int id)
        {
			var thisProduct = _db.Products.FirstOrDefault(x => x.ProductId == id);
            return View(thisProduct);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
			var thisProduct = _db.Products.FirstOrDefault(x => x.ProductId == id);
            _db.Remove(thisProduct);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MarioProducts/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using MarioProducts.Models;
using System.Diagnostics.Contracts;


namespace MarioProducts.Controllers
{
    public class ReviewController : Controller
    {
        private readonly MarioProductsDbContext _db;
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;

        public ReviewController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, MarioProductsDbContext db)
		{
			_userManager = userManager;
			_signInManager = signInManager;
			_db = db;
		}
   
        public IActionResult Index(int id)
        {
            var allReviews = _db.Reviews
                                .Include(reviews => reviews.ProductId == id).ToList();
            return Json(allReviews);
        }

        public IActionResult Create()
        {
			ViewBag.ProductId = new SelectList(_db.Products, "ProductId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(string author, string contentBody, int rating, int id)
        {
            var newReview = new Review(author, contentBody, rating, id);

            if (ModelState.IsValid)
            {
				_db.Reviews.Add(newReview);
				_db.SaveChanges(); 
            }

            return Json(newReview);
        }

        public IActionResult Edit(int id)
        {
			ViewBag.ProductId = new SelectList(_db.Products, "ProductId", "Name");
            var thisReview = _db.Reviews.Include(x => x.Products)
                                       .FirstOrDefault(x => x.ReviewId == id);
            return View(thisReview);
        }

        [HttpPost]
        public IActionResult Edit(Review review)
        {
            _db.Entry(review).State = EntityState.Modified;
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var thisReview = _db.Reviews.Include(x => x.Products)
									   .FirstOrDefault(x => x.ReviewId == id);
            return View(thisReview);
                                        
        }

		public IActionResult Delete(int reviewId, int productId)
		{
			var thisReview = _db.Reviews.Include(x => x.Products)
									  .FirstOrDefault(x => x.ReviewId == reviewId);
            return View(thisReview);
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult DeleteConfirmed(int reviewId, int productId)
		{
			var thisReview = _db.Reviews.FirstOrDefault(review => review.ReviewId == reviewId);
			_db.Remove(thisReview);
            _db.SaveChanges();
            return RedirectToAction("Details", "Product", new { id = productId});
		}
    }
}

MarioProducts/Views/Product/Create.cshtml
@model MarioProducts.Models.Product

@{
    ViewData["Title"] = "Product - Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="add-product-index">
    <h1 class="create-title">Add new product</h1>

    <div class="container form">
        @using (Html.BeginForm())
        {
            <div class="card">
                @Html.LabelFor(model => model.Name)
                @Html.EditorFor(model => model.Name)
                <div class="margin"></div>
                @Html.LabelFor(model => model.Cost)
                @Html.EditorFor(model => model.Cost)
                <div class="margin"></div>
                @Html.LabelFor(model => model.CountryOfOrigin)
                @Html.EditorFor(model => model.CountryOfOrigin)
                <div class="margin"></div>
                @Html.HiddenFor(model => model.CreateDate)

                <input type="submit" value="Save" class="btn submit-btn"/>
            </div>
		}
    </div>
</div>

MarioProducts/Views/Product/Delete.cshtml
@model MarioProducts.Models.Product

@{
    ViewData["Title"] = "Product - Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="delete-view">
    <h1 class="home-title">Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h1>

    @using (Html.BeginForm())
    {
        <div class="center">
             <input type="submit" class="btn delete-confirm" value="Confirm" onclick="location.href='@Url.Action("Delete", new{ id = Model.ProductId})'"/>
             <input type="submit" class="btn" value="Cancel" onclick="location.href='Url.Action("Details", new {id = Model.ProductId})'"/>
	    </div>
    }
</div>

MarioProducts/Views/Product/Details.cshtml
@model MarioProducts.Models.Product

@{
    ViewData["Title"] = "Product - Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script>
		$(document).ready(function() {
           $(".add-review").submit(function(event) {
		        event.preventDefault();
                $.ajax({
                    url: '@Url.Action("Create", "Review", new{ id = Model.ProductId})',
		            type: 'POST',
		            dataType: 'json',
		            data: $(this).serialize(),
		            success: function (result) {
			            var newReview = '<p>' + '<strong><h5>Your Newly Added Review</h5></strong>' + '<strong>Author: </strong>' + result.author + '<br>' + '<strong>Review: </strong>' + result.contentBody + '<br>' + '<strong>Rating: </strong>' + result.rating + '</p>';
		                $("#show-recent").html(newReview);
			            $("#close-btn").show();
		            }
		        })
		    });
		});
    </script>
</head>

<body>
    <h1 class="product-title">@Html.DisplayFor(model => model.Name) Details</h1>

    @if (User.Identity.IsAuthenticated)
    {
		<div class="admin-detail-btns">
            <p>@Html.ActionLink("Edit", "Edit", new {id = Model.ProductId}) | @Html.ActionLink("Delete", "Delete", new {id = Model.ProductId})</p>
        </div>    
	}

   <div class="container">
        <div class="card">
            <p>@Html.DisplayNameFor(model => model.Cost): $@Html.DisplayFor(model => model.Cost)</p>
            <p>Country of Origin: @Html.DisplayFor(model => model.CountryOfOrigin)</p>
            <p>Average Rating: @Model.AverageRating()</p>
        </div>
	
        <div class="card">
        	<h4>Write a review for the product: @Html.DisplayFor(model => model.Name)</h4>
        	<form action='(Create", "Review", new{ id = Model.ProductId})' class="add-review">
                <label for="review">Author</label>
        		<input type="text" name="author"/>
        		<label for="review">Review</label>
                <input type="text" minlength="50" maxlength="250" name="contentBody"/>
        		<label for="review">Add Rating (1-5)</label>
                <input type="number" min="1" max="5" name="rating"/>
        		<button type="submit" class="btn btn-info">Add Review</button>
        	</form>

        	<div id="show-recent"></div>
			<div id="close-btn"><input type="button" class="btn btn-danger" value="Close" onclick="location.href='@Url.Action("Details", "Product", new { id = Model.ProductId})'"/></div>

         </div>
			
    <h3 class="get-reviews">View All Reviews</h3>		
	@foreach(var review in Model.Reviews)
		{
			<div class="card">
                <div class="card-header">@review.Author</div>
			    <div class="card-block">@review.ContentBody
                <br>
					@review.Rating
				</div>
            
                @if(User.Identity.IsAuthenticated)
    			{
                    @Html.ActionLink("Delete", "Delete", "Review", new {reviewId = review.ReviewId, productId = review.ProductId})
    			}
		
				</div>
		}  
   </div>
</body>
</html>

MarioProducts/Views/Product/Edit.cshtml
@model MarioProducts.Models.Product

@{
    ViewData["Title"] = "Product - Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add new product</h1>


@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.Cost)
    @Html.EditorFor(model => model.Cost)

    @Html.LabelFor(model => model.CountryOfOrigin)
    @Html.EditorFor(model => model.CountryOfOrigin)

    @Html.HiddenFor(model => model.ProductId)

    <input type="submit" value="Save"/>
}

MarioProducts/Views/Product/Index.cshtml
@model IEnumerable<MarioProducts.Models.Product>

@{
    ViewData["Title"] = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="product-index">
    <h1 class="product-title">Products</h1>

	<div class="container">
     @if (User.Identity.IsAuthenticated)
    {
        <input type="button" id="create-btn" class="btn add-product-btn" value="Add New Product" onclick="location.href='@Url.Action("Create", "Product")'"/>
	}
	<br>

    @foreach (var product in Model)
    {   
      <div class="card product-cards" style="width: 20rem; text-align:center;display:inline-block;">
        <div class="card-block">
          <h4 class="card-title ">@Html.DisplayFor(model => product.Name) </h4>
		  <input type="button" id="create-btn" class="btn product-btn" value="Product Details" onclick="location.href='@Url.Action("Details", new {id = product.ProductId})'"/>
          <p class="card-text"><small class="text-muted">Date Posted: @product.CreateDate</small></p>
        </div>
      </div>	
    }
	</div>
   
</div>